import Head from 'next/head'
import axios from 'axios'
import {useState} from 'react'
import {BsSearch} from 'react-icons'

export default function Home() {

  const url = `https://api.openweathermap.org/data/2.5/weather?q=stockton&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

  const[city , setCity] = useState('')
  const[weather, setWeather] = useState({})
  const [loading, setLoading] = useState(false)

  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data)
      console.log(response.data)
    })
  }

  return (
    <div>

      <Head>
        <title>Weather - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}
